"""
Django settings for moviereviewsystem project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# ---------------------------
# 🧱 Base Directory
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# ⚙️ Basic Config
# ---------------------------
SECRET_KEY = 'django-insecure-9itzz&umm!1amqb&$7g0fkp_943a^w%((b-ssgui4-t31==&v5'
DEBUG = True
ALLOWED_HOSTS = []

# ---------------------------
# 📦 Installed Apps
# ---------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your future apps:
    'app',
    # 'movies',
    # 'users',
]

# ---------------------------
# 🧩 Middleware
# ---------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------------------------
# 🚀 URL / WSGI
# ---------------------------
ROOT_URLCONF = 'moviereviewsystem.urls'
WSGI_APPLICATION = 'moviereviewsystem.wsgi.application'

# ---------------------------
# 🧠 Templates
# ---------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates folder
        'APP_DIRS': True,                  # Enables per-app templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ---------------------------
# 🗃️ Database
# ---------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------
# 🔒 Password Validation
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------
# 🌍 Internationalization
# ---------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'  # optional: change to your local time zone
USE_I18N = True
USE_TZ = True

# ---------------------------
# 🖼️ Static Files
# ---------------------------
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # Global static folder
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # Where collectstatic gathers files

# ---------------------------
# 🧩 Default Auto Field
# ---------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
